# Generated by Django 2.2.1 on 2019-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=250)),
                ('apellido_paterno_usuario', models.CharField(max_length=250)),
                ('apellido_materno_usuario', models.CharField(max_length=250)),
                ('correo_usuario', models.EmailField(max_length=254)),
                ('contrasena_usuario', models.TextField()),
            ],
        ),
    ]
