# Generated by Django 2.2.1 on 2019-07-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espanol',
            name='existe_frances',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='espanol',
            name='existe_ingles',
            field=models.IntegerField(default='0'),
        ),
    ]
