# Generated by Django 2.2.1 on 2019-08-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20190719_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espanol',
            name='existe_frances',
        ),
        migrations.RemoveField(
            model_name='espanol',
            name='existe_ingles',
        ),
    ]
