# Generated by Django 2.2.1 on 2019-08-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_auto_20190808_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frances',
        ),
    ]
