# Generated by Django 2.2.1 on 2019-08-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_delete_frances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espanol',
            name='presentacion_producto',
        ),
        migrations.AddField(
            model_name='espanol',
            name='foto_produto',
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_de_medida', models.CharField(max_length=250)),
                ('cantidad', models.FloatField()),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.Espanol')),
            ],
        ),
    ]
